port: "8080"
log_level: "info"
torrent_timeout: "180s"
max_connections: 2000
download_rate_limit: 104857600  # 100 MB/s (ajusta según el ancho de banda disponible)
upload_rate_limit: 1024  # Reducido a 1 KB/s (prácticamente nulo)
cache_size: 50000
cleanup_interval: "125m"
hls_segment_duration: 4
download_dir: "/Users/oscarvalois/Downloads/torrents"
keep_files: true
max_download_time: "12h"
dht_node_count: 2000
peer_id_prefix: "-TD2024-"
user_agent: "TorrentDownloader/2.1"
tcp_port: 6881
udp_port: 6882
enable_upnp: true
enable_dht: true
enable_pex: true
enable_lsd: true
max_open_files: 4096
write_buffer_size: 8388608
read_buffer_size: 8388608
max_peers_per_torrent: 300
max_active_torrents: 100
seed_ratio_limit: 0.0001  # Reducido al mínimo
seed_time_limit: "1m"  # Reducido a 1 minuto
piece_buffer_size: 524288
enable_scrape: true
tracker_timeout: "45s"
enable_metadata_exchange: true
max_metadata_size: 20971520

# Nuevas configuraciones
connection_pool_size: 1000
max_incoming_connections: 1000
max_outgoing_connections: 1000
read_cache_size: 67108864
write_cache_size: 67108864
max_piece_handlers: 100
max_request_blocks: 250
request_timeout: "20s"
piece_timeout: "30s"
max_peer_upload_slots: 1  # Reducido al mínimo
max_peer_download_slots: 4
max_active_downloads: 50
max_active_seeds: 1  # Reducido al mínimo
enable_ip_filtering: true
ip_filter_file: "/etc/torrent/ipfilter.dat"
enable_bandwidth_management: true
bandwidth_management_interval: "1s"