# Network and Server Configuration
port: "8080"
log_level: "debug"
max_connections: 5000
download_rate_limit: 209715200
upload_rate_limit: 1048576
rate_limit: 1000
tcp_port: 6881
udp_port: 6882
enable_upnp: true
enable_dht: true
enable_pex: true
enable_lsd: true

# Torrent Client Configuration
peer_id_prefix: "-TD2024-"
user_agent: "TorrentStreamer/3.0"
dht_node_count: 5000
max_peers_per_torrent: 500
max_active_torrents: 200
seed_ratio_limit: 0.1
seed_time_limit: "5m"
max_metadata_size: 20971520
enable_scrape: true
tracker_timeout: "30s"
enable_metadata_exchange: true

# Connection and Peer Management
connection_pool_size: 2000
max_incoming_connections: 2500
max_outgoing_connections: 2500
max_peer_upload_slots: 2
max_peer_download_slots: 8
max_active_downloads: 100
max_active_seeds: 10
enable_ip_filtering: true
ip_filter_file: "/etc/torrent/ipfilter.dat"

# Performance Tuning
max_open_files: 8192
write_buffer_size: 16777216
read_buffer_size: 16777216
piece_buffer_size: 1048576
write_cache_size: 134217728
read_cache_size: 268435456
max_piece_handlers: 200
max_request_blocks: 500

# Streaming Optimization
buffer_size: 41943040
prefetch_size: 20
stream_chunk_size: 2097152
hls_segment_duration: 4
piece_preload_count: 10
piece_read_ahead: 10

# Resource Management
cache_size: 100000
cleanup_interval: "120m"
download_dir: "/downloads"
keep_files: false
max_download_time: "24h"
enable_bandwidth_management: true
bandwidth_management_interval: "500ms"

# Concurrency and Request Handling
max_concurrent_torrents: 100
max_pending_requests: 400
piece_selection_window: 100
max_peers: 100

# Timeouts and Retries
wait_timeout: "20s"
request_timeout: "60s"
piece_timeout: "20s"
torrent_timeout: "10m"
metadata_timeout: "2m"
poll_interval: "50ms"
stats_interval: "1m"
initial_retry_wait: "50ms"
max_retry_wait: "3s"
max_retries: 8
initial_retry_delay: "500ms"
max_retry_delay: "30s"
retry_backoff_factor: 1.5
retry_delay: "50ms"

# Speed Limits
max_download_speed: 209715200
max_upload_speed: 10485760

# Caching
piece_cache_size: 2000
session_timeout: "180m"

# New fields (added from the Go struct)
cors_allowed_origins:
  - "https://chillflix.fly.dev"
  - "http://localhost:5173"
cache_ttl: "5m"
server_read_timeout: "15s"
server_write_timeout: "15s"
server_idle_timeout: "60s"
circuit_breaker_timeout: "30s"
circuit_breaker_max_failures: 5
circuit_breaker_max_requests: 100
circuit_breaker_interval: "1m"
circuit_breaker_min_requests: 10
circuit_breaker_error_threshold: 0.5
shutdown_timeout: "30s"
rate_limit_burst: 1000
initial_rate_limit: 1000