# fly.toml app configuration file generated for mpyr on 2024-08-08T11:42:03-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mpyr'
primary_region = 'qro'

[build]

[env]
  JWT_SECRET = ''
  TURNSTILE_SECRET = ''

[[mounts]]
  source = 'tmp'
  destination = '/tmp'
  initial_size = '20gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
